<?php

namespace DataConsolidation\CustomNodesBundle\Entity\DefaultEntityManager\Base;

use Doctrine\ORM\EntityRepository;

/**
 * DataSourceToDiagramMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSourceToDiagramMappingRepository extends EntityRepository
{
    public function findAllByDiagramName($diagramName)
    {
        $results = $this->findBy(
            array('diagram' => $diagramName)
        );
        return $results;
    }

    public function findAllByDiagramAndDataSourceNames($diagramName, $dataSource = NULL)
    {
        $criteria = array(
            'diagram' => $diagramName,
        );
        if (!empty($dataSource)) {
            $criteria['dataSource'] = $dataSource;
        }

        $results = $this->findBy($criteria);
        return $results;
    }
}
