data_consolidation_diagram_data_fetcher:
    resource: "@DataConsolidationDiagramDataFetcherBundle/Resources/config/routing.yml"
    prefix:   /data-fetcher/

data_consolidation_database_configuration:
    resource: "@DataConsolidationDatabaseConfigurationBundle/Resources/config/routing.yml"
    prefix:   /admin/database-configuration/

data_consolidation_custom_nodes:
    resource: "@DataConsolidationCustomNodesBundle/Resources/config/routing.yml"
    prefix:   /admin/custom-nodes/

air_measurement_admin:
    resource: "@AirMeasurementAdminBundle/Resources/config/routing.yml"
    prefix:   /

air_measurement_user:
    resource: "@AirMeasurementUserBundle/Resources/config/routing.yml"
    prefix:   /

air_measurement_diagram:
    resource: "@AirMeasurementDiagramBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile