<?php

namespace AirMeasurement\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QualityConditionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualityConditionsRepository extends EntityRepository
{
}
